In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt 
import seaborn as sns

#Data preprocessing
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

#For modeling
# import tensorflow as tf
from sklearn.metrics import confusion_matrix, accuracy_score


In [2]:
df = pd.read_csv("Churn_Modelling.csv");

In [3]:
X=df.iloc[:,3:-1].values #All the rows except the last one
y=df.iloc[:,-1].values #Existed column

In [4]:
le=LabelEncoder()
X[:,2]=le.fit_transform(X[:,2]) #all rows in Third column (Gender)

In [5]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [6]:
X_train, X_test, y_train, y_test =train_test_split(X,y,test_size=0.2, random_state=0)

In [7]:
sc = StandardScaler() #makes the range of variable from +3 to -3
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [8]:
import tensorflow as tf

In [9]:
ann =tf.keras.models.Sequential()

In [10]:
ann.add(tf.keras.layers.Dense(units=6,activation='relu'))
ann.add(tf.keras.layers.Dense(units=6,activation='relu'))

In [11]:
ann.add(tf.keras.layers.Dense(units=1,activation='sigmoid'))

In [12]:
ann.compile(optimizer='adam',loss='binary_crossentropy', metrics=['accuracy'])

In [13]:
ann.fit(X_train, y_train, batch_size=32, epochs=100)

Epoch 1/100
250/250 [==============================] - 2s 4ms/step - loss: 0.5892 - accuracy: 0.7611
Epoch 2/100
250/250 [==============================] - 1s 4ms/step - loss: 0.4900 - accuracy: 0.7977
Epoch 3/100
250/250 [==============================] - 1s 4ms/step - loss: 0.4373 - accuracy: 0.8101
Epoch 4/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3980 - accuracy: 0.8332
Epoch 5/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3803 - accuracy: 0.8418
Epoch 6/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3717 - accuracy: 0.8440
Epoch 7/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3663 - accuracy: 0.8471
Epoch 8/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3629 - accuracy: 0.8486
Epoch 9/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3601 - accuracy: 0.8491
Epoch 10/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3579 - accura

250/250 [==============================] - 1s 6ms/step - loss: 0.3357 - accuracy: 0.8626
Epoch 82/100
250/250 [==============================] - 1s 4ms/step - loss: 0.3352 - accuracy: 0.8636
Epoch 83/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3351 - accuracy: 0.8636
Epoch 84/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3351 - accuracy: 0.8637
Epoch 85/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3349 - accuracy: 0.8627
Epoch 86/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3356 - accuracy: 0.8631
Epoch 87/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3352 - accuracy: 0.8645
Epoch 88/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3350 - accuracy: 0.8644
Epoch 89/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3349 - accuracy: 0.8630
Epoch 90/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3350 - accuracy: 

In [14]:
print(ann.predict(sc.transform([[1,0,0,600,1,40,3,60000,2,1,1,50000]])) > 0.5)

1/1 [==============================] - 0s 231ms/step
[[False]]


In [15]:
y_pred=ann.predict(X_test)
y_pred = (y_pred >0.5)

63/63 [==============================] - 0s 2ms/step


In [16]:
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


In [17]:
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[1501   94]
 [ 186  219]]


0.86

# ANN Dropout

In [23]:
ann =tf.keras.models.Sequential()

ann.add(tf.keras.layers.Dense(units=6,activation='relu'))

ann.add(tf.keras.layers.Dropout(0.4))

ann.add(tf.keras.layers.Dense(units=6,activation='relu'))

ann.add(tf.keras.layers.Dropout(0.3))

ann.add(tf.keras.layers.Dense(units=1,activation='sigmoid'))

ann.compile(optimizer='adam',loss='binary_crossentropy', metrics=['accuracy'])

ann.fit(X_train, y_train, batch_size=32, epochs=100)

Epoch 1/100
250/250 [==============================] - 2s 3ms/step - loss: 0.6288 - accuracy: 0.7275
Epoch 2/100
250/250 [==============================] - 1s 3ms/step - loss: 0.5196 - accuracy: 0.7926
Epoch 3/100
250/250 [==============================] - 1s 3ms/step - loss: 0.4925 - accuracy: 0.7945
Epoch 4/100
250/250 [==============================] - 1s 3ms/step - loss: 0.4841 - accuracy: 0.7951
Epoch 5/100
250/250 [==============================] - 1s 3ms/step - loss: 0.4769 - accuracy: 0.7952
Epoch 6/100
250/250 [==============================] - 1s 4ms/step - loss: 0.4677 - accuracy: 0.7958
Epoch 7/100
250/250 [==============================] - 1s 3ms/step - loss: 0.4593 - accuracy: 0.8001
Epoch 8/100
250/250 [==============================] - 1s 3ms/step - loss: 0.4561 - accuracy: 0.8036
Epoch 9/100
250/250 [==============================] - 1s 3ms/step - loss: 0.4505 - accuracy: 0.8062
Epoch 10/100
250/250 [==============================] - 1s 3ms/step - loss: 0.4509 - accura

250/250 [==============================] - 1s 5ms/step - loss: 0.4158 - accuracy: 0.8246
Epoch 82/100
250/250 [==============================] - 1s 5ms/step - loss: 0.4181 - accuracy: 0.8220
Epoch 83/100
250/250 [==============================] - 1s 6ms/step - loss: 0.4120 - accuracy: 0.8265
Epoch 84/100
250/250 [==============================] - 2s 6ms/step - loss: 0.4168 - accuracy: 0.8221
Epoch 85/100
250/250 [==============================] - 1s 6ms/step - loss: 0.4186 - accuracy: 0.8214
Epoch 86/100
250/250 [==============================] - 1s 6ms/step - loss: 0.4143 - accuracy: 0.8250
Epoch 87/100
250/250 [==============================] - 1s 5ms/step - loss: 0.4141 - accuracy: 0.8215
Epoch 88/100
250/250 [==============================] - 1s 6ms/step - loss: 0.4208 - accuracy: 0.8216
Epoch 89/100
250/250 [==============================] - 1s 5ms/step - loss: 0.4080 - accuracy: 0.8259
Epoch 90/100
250/250 [==============================] - 1s 5ms/step - loss: 0.4176 - accuracy: 

In [24]:
y_pred=ann.predict(X_test)
y_pred = (y_pred >0.5)

y_pred

63/63 [==============================] - 0s 2ms/step


array([[False],
       [False],
       [False],
       ...,
       [False],
       [False],
       [False]])

In [25]:
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[1585   10]
 [ 303  102]]


0.8435