In [1]:
import numpy as np
import pandas as pd

## 1. Extract all odd numbers from arr

In [7]:
arr1 = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr1[arr1 % 2 == 1]

array([1, 3, 5, 7, 9])

## 2. Replace all odd numbers in arr with -1

In [10]:
arr2 = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr2[arr2 % 2 == 1] = -1
arr2

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

## 3. Convert a 1D array to a 2D array with 2 rows

In [15]:
arr3 = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr3 = arr3.reshape(2,5)
arr3

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

## 4. Get the common items between a and b

In [17]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

np.intersect1d(a,b)

array([2, 4])

## 5. Create a 2D array containing random floats between 5 and 10.

arr5 = np.linspace(5,10,8)
arr5 = arr5.reshape(2,4)
arr5

## 6. Write a Pandas program to create and display a DataFrame from a specified dictionary data which.

In [32]:
data = {
    "name" : ["Anastasia","Dima","Katherine","James","Emily","Michael","Matthew","Laura","Kevin","Jonas",np.nan],
    "score" : [12.5,9.0,np.nan,np.nan,9.0,20.0,14.5,np.nan,8.0,19.0,np.nan],
    "attempts" : [1.0,3.0,2.0,3.0,2.0,3.0,1.0,1.0,2.0,1.0,np.nan],
    "qualify" : ["yes","no","yes","no","no","yes","yes","no","no","yes",np.nan]
}
df = pd.DataFrame(data,index=["a","b","c","d","e","f","g","h","i","j","k"])
df

name  score  attempts qualify
a  Anastasia   12.5       1.0     yes
b       Dima    9.0       3.0      no
c  Katherine    NaN       2.0     yes
d      James    NaN       3.0      no
e      Emily    9.0       2.0      no
f    Michael   20.0       3.0     yes
g    Matthew   14.5       1.0     yes
h      Laura    NaN       1.0      no
i      Kevin    8.0       2.0      no
j      Jonas   19.0       1.0     yes
k        NaN    NaN       NaN     NaN

## 7. Write a Pandas program to get the first 3 rows of a given DataFrame.

In [34]:
df.head(3)

name  score  attempts qualify   exam date
a  Anastasia   12.5       1.0     yes  17/05/2002
b       Dima    9.0       3.0      no  17/05/2002
c  Katherine    NaN       2.0     yes  17/05/2002

## 8. Write a Pandas program to select the 'name' and 'score' columns from the following DataFrame.

In [39]:
df[["name","score"]]

name  score
a  Anastasia   12.5
b       Dima    9.0
c  Katherine    NaN
d      James    NaN
e      Emily    9.0
f    Michael   20.0
g    Matthew   14.5
h      Laura    NaN
i      Kevin    8.0
j      Jonas   19.0
k        NaN    NaN

## 9. Write a Pandas program to select the specified columns and rows from a given data frame.

In [78]:
df[["name","score"]].loc[["a","b","g"]]

name  score
a  Anastasia   12.5
b       Dima    9.0
g    Matthew   14.5

## 10. Write a Pandas program to add new column named ‘exam date’ of type date and time to existing Dataframe

In [92]:
# df = df.drop(["exam date"],axis=1) 
df["exam date"] = ["17/05/2002","17/06/2002","17/02/2002","17/03/2002","17/01/2002","17/08/2002","17/07/2002","17/11/2002","17/12/2002","17/10/2002","17/10/2002","17/10/2002"]
df["exam date"] = pd.to_datetime(df["exam date"])
df

name  score  attempts qualify exam year exam month  exam date
a  Anastasia   12.5       1.0     yes      1998         05 2002-05-17
b       Dima    9.0       3.0      no      2001         06 2002-06-17
c  Katherine    NaN       2.0     yes      2003         02 2002-02-17
d      James   11.5       3.0      no      2004         03 2002-03-17
e      Emily    9.0       2.0      no      2005         01 2002-01-17
f    Michael   20.0       3.0     yes      2006         06 2002-08-17
g    Matthew   14.5       1.0     yes      2007         08 2002-07-17
h      Laura    NaN       1.0      no      2008         07 2002-11-17
i      Kevin    8.0       2.0      no      2009         11 2002-12-17
j      Jonas   19.0       1.0     yes      2010         12 2002-10-17
k        NaN    NaN       NaN     NaN      2011         10 2002-10-17
l       test   12.0       5.0     yes      2001         03 2002-10-17

## 11. Write a Pandas program to insert two new columns ‘exam month’ and ‘exam year’ in a given DataFrame.

In [44]:
df["exam month"] = ["05","06","02","03","01","06","08","07","11","12","10"]
df
df["exam year"] = ["1998","2001","2003","2004","2005","2006","2007","2008","2009","2010","2011"]
df

name  score  attempts qualify   exam date exam year exam month
a  Anastasia   12.5       1.0     yes  17/05/2002      1998         05
b       Dima    9.0       3.0      no  17/06/2002      2001         06
c  Katherine    NaN       2.0     yes  17/02/2002      2003         02
d      James    NaN       3.0      no  17/03/2002      2004         03
e      Emily    9.0       2.0      no  17/01/2002      2005         01
f    Michael   20.0       3.0     yes  17/06/2002      2006         06
g    Matthew   14.5       1.0     yes  17/08/2002      2007         08
h      Laura    NaN       1.0      no  17/07/2002      2008         07
i      Kevin    8.0       2.0      no  17/11/2002      2009         11
j      Jonas   19.0       1.0     yes  17/12/2002      2010         12
k        NaN    NaN       NaN     NaN  17/10/2002      2011         10

## 12. Write a Pandas program to select the rows where the score is missing

In [53]:
df[df["score"].isnull()]

name  score  attempts qualify   exam date exam year exam month
c  Katherine    NaN       2.0     yes  17/02/2002      2003         02
d      James    NaN       3.0      no  17/03/2002      2004         03
h      Laura    NaN       1.0      no  17/07/2002      2008         07
k        NaN    NaN       NaN     NaN  17/10/2002      2011         10

## 13. Write a Pandas program to select the rows where number of attempts in the examination is less than 2 and score greater than 15.

In [56]:
df[(df["attempts"] > 2) & (df["score"] > 15)]

name  score  attempts qualify   exam date exam year exam month
f  Michael   20.0       3.0     yes  17/06/2002      2006         06

## 14. Write a Pandas program to change the score in row indexed’d’ to 11.5.

In [64]:
df.loc["d","score"] = 11.5
df.loc["d"]

name               James
score               11.5
attempts             3.0
qualify               no
exam date     17/03/2002
exam year           2004
exam month            03
Name: d, dtype: object

## 15. Write a Pandas program to calculate the sum of the examination attempts by the students.

In [65]:
df["attempts"].sum()

19.0

## 16. Write a Pandas program to calculate the mean score for each different student in DataFrame and store it in new column named ‘mean score’.

In [69]:
print("Students Mean Score is {0}".format(df["score"].mean()))

Students Mean Score is 12.833333333333334


## 17. Write a Pandas program to append a new row 'k' to data frame with given values for each column.

In [67]:
df.loc["l"] = ["test",12,5.0,"yes","12,02,2001","2001","03"]
df

name  score  attempts qualify   exam date exam year exam month
a  Anastasia   12.5       1.0     yes  17/05/2002      1998         05
b       Dima    9.0       3.0      no  17/06/2002      2001         06
c  Katherine    NaN       2.0     yes  17/02/2002      2003         02
d      James   11.5       3.0      no  17/03/2002      2004         03
e      Emily    9.0       2.0      no  17/01/2002      2005         01
f    Michael   20.0       3.0     yes  17/06/2002      2006         06
g    Matthew   14.5       1.0     yes  17/08/2002      2007         08
h      Laura    NaN       1.0      no  17/07/2002      2008         07
i      Kevin    8.0       2.0      no  17/11/2002      2009         11
j      Jonas   19.0       1.0     yes  17/12/2002      2010         12
k        NaN    NaN       NaN     NaN  17/10/2002      2011         10
l       test   12.0       5.0     yes  12,02,2001      2001         03