In [2]:
import numpy as np #--> np is alias name of numpy

In [4]:
x = np.array([1]) # --> Zero DArray

### 1D Array

In [5]:
arr1 = np.array([1,2,3,4,5,6])
print(arr1)

[1 2 3 4 5 6]


### 2D Array

In [6]:
arr2 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


### 3D Array

In [7]:
arr3 = np.array([ [[1,2,3],[4,5,6],[7,8,9]] , [[1,2,3],[4,5,6],[7,8,9]] , [[1,2,3],[4,5,6],[7,8,9]]  ])
print(arr3) 

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]


### Making array using Lists

In [8]:
lst1 = ['A','B','C']
lst2 = ['D','E','F']
lst3 = ['G','H','I']
lst4 = ['G','H','I','J']

#1D array
arr1D = np.array(lst1)
print("1D ArraY :",end=" ")
print(arr1D)
print(type(arr1D))
print(arr1D.dtype)
print(arr1D.shape)

print("------------------------")
print("------------------------")


#2D Array
arr2D = np.array([ lst1,lst2,lst3 ])
print("2D ArraY :",end="\n\n")
print(arr2D)
print(type(arr2D))
print(arr2D.dtype)
print(arr2D.shape)

print("------------------------")
print("------------------------")


#3D Array
arr3D = np.array([ [ lst1,lst2,lst3 ] , [ lst1,lst2,lst3 ] , [ lst1,lst2,lst3 ] ])
print("3D ArraY :",end="\n\n")
print(arr3D)
print(type(arr3D))
print(arr3D.dtype)
print(arr3D.shape)



1D ArraY : ['A' 'B' 'C']
<class 'numpy.ndarray'>
<U1
(3,)
------------------------
------------------------
2D ArraY :

[['A' 'B' 'C']
 ['D' 'E' 'F']
 ['G' 'H' 'I']]
<class 'numpy.ndarray'>
<U1
(3, 3)
------------------------
------------------------
3D ArraY :

[[['A' 'B' 'C']
  ['D' 'E' 'F']
  ['G' 'H' 'I']]

 [['A' 'B' 'C']
  ['D' 'E' 'F']
  ['G' 'H' 'I']]

 [['A' 'B' 'C']
  ['D' 'E' 'F']
  ['G' 'H' 'I']]]
<class 'numpy.ndarray'>
<U1
(3, 3, 3)


### Accessing Array

In [9]:
#1.
print(arr3D[0,1,1])
print("------------------------")

#2. 
print(arr3D[0][1][2])
print("------------------------")

#3.
print(arr3D[0,1:3,1:3])
print("------------------------")

#4.
print(arr3D[:3,0:,1:3])
print("------------------------")



E
------------------------
F
------------------------
[['E' 'F']
 ['H' 'I']]
------------------------
[[['B' 'C']
  ['E' 'F']
  ['H' 'I']]

 [['B' 'C']
  ['E' 'F']
  ['H' 'I']]

 [['B' 'C']
  ['E' 'F']
  ['H' 'I']]]
------------------------


### 

In [10]:
#5.
print(arr2[0:2,1:3])
print("------------------------")
print(arr2)
print("------------------------")

print(arr2[0:3][0:2]) #pending
print("------------------------")

#6.
print(arr2[0:3,1:3])
print("------------------------")

print(arr3[0:3,0:3,1:3])

[[2 3]
 [5 6]]
------------------------
[[1 2 3]
 [4 5 6]
 [7 8 9]]
------------------------
[[1 2 3]
 [4 5 6]]
------------------------
[[2 3]
 [5 6]
 [8 9]]
------------------------
[[[2 3]
  [5 6]
  [8 9]]

 [[2 3]
  [5 6]
  [8 9]]

 [[2 3]
  [5 6]
  [8 9]]]


In [11]:
print(arr2[0:3][1:2])

[[4 5 6]]


## Negative 

In [24]:
print(arr2)
print("-----------------")
print(arr2[-1,-1])
print("-----------------")
print(arr2[-3:-1,-3:-1])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
-----------------
9
-----------------
[[1 2]
 [4 5]]


## Range

In [30]:
arr_range = np.array([[x for x in range(0,7,2)],[x for x in range(0,7,2)],[x for x in range(0,7,2)]])
print(arr_range);

[[0 2 4 6]
 [0 2 4 6]
 [0 2 4 6]]


In [44]:
print("\n---------------------")
print("Before Reshape")
print("---------------------")
print(arr_range.shape)

print("\n---------------------")
print("After Reshape")
print("---------------------")
arr_range = arr_range.reshape(4,3)
print(arr_range)
print("---------------------")
print("New Shape is ", arr_range.shape)


---------------------
Before Reshape
---------------------
(4, 3)

---------------------
After Reshape
---------------------
[[0 2 4]
 [6 0 2]
 [4 6 0]
 [2 4 6]]
---------------------
Shape is  (4, 3)


In [47]:
arr_odd = np.array([x for x in range(1,8)])
print(arr_odd)

arr_odd = arr_odd.reshape(2,3)
print(arr_odd)

[1 2 3 4 5 6 7]


ValueError: cannot reshape array of size 7 into shape (2,3)

### With Looping

In [73]:
arr_for = np.array([[x for x in range(0,6,2)],[x for x in range(0,6,2)],[x for x in range(0,6,2)]])

print("---------------")
print(arr_for)
print("---------------")

for i in range(0,len(arr_for)):
    for j in range(0,len(arr_for[i])):
        print("arr_for[{0}][{1}] = ".format(i,j),arr_for[i,j])

---------------
[[0 2 4]
 [0 2 4]
 [0 2 4]]
---------------
arr_for[0][0] =  0
arr_for[0][1] =  2
arr_for[0][2] =  4
arr_for[1][0] =  0
arr_for[1][1] =  2
arr_for[1][2] =  4
arr_for[2][0] =  0
arr_for[2][1] =  2
arr_for[2][2] =  4


### Avoid For loops for fetching array elements

In [71]:
for x in np.nditer(arr_for):
    print(x,end=" ")

0 2 4 0 2 4 0 2 4 

# Creating NumPy Arrays 

<ul>
    <li>np.ones(3,2)</li>
    <li>np.zeros()</li>
    <li>np.zeros_like()</li>
    <li>np.arange()</li>
    <li>np.reshape()</li>
    <li>np.ndim</li>
    <li>np.random.indint()</li>
    <li>np.linspace()</li>
    <li>np.full() Create constant Number on 'n'</li>
    <li>np.tile()</li>
    <li>np.eye()</li>
</ul>

In [76]:
# np.ones()
arr = np.ones(shape=(3,2))
print(arr)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [78]:
# np.zeros()

arr = np.zeros(shape=(3,3))
print(arr)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [81]:
# np.zeros_like()

arr_n = [[1,2,3],[4,5,6],[7,8,9]]
arr = np.zeros_like(arr_n)
print(arr)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [12]:
# np.arange()

arr = np.arange(1,10)
arr = arr.reshape(3,3)
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [106]:
# np.random()

arr = np.random.randint(1,10,9)
arr = arr.reshape(3,3)
print(arr)

[[2 7 4]
 [9 7 4]
 [4 6 6]]


In [7]:
# np.linspace()

arr = np.linspace(1,10,16)
arr = arr.reshape(4,4)
print(arr)

[[ 1.   1.6  2.2  2.8]
 [ 3.4  4.   4.6  5.2]
 [ 5.8  6.4  7.   7.6]
 [ 8.2  8.8  9.4 10. ]]


In [115]:
# np.full()

arr = np.full((3,3),"*")
# arr = arr.reshape(3,3)
print(arr)

[['*' '*' '*']
 ['*' '*' '*']
 ['*' '*' '*']]


In [9]:
# np.tile()

arr = np.tile(3,2)
# arr = arr.reshape(3,3)
print(arr)

[3 3]


In [25]:
a = np.array([[1,2,3],[1,2,3],[1,2,3]])
b = np.array([[1,2,3],[1,2,3],[1,2,3]])
np.subtract(a,b)

a.sum()

h = a.copy()

i = np.transpose(a)

a.ravel()

array([1, 2, 3, 1, 2, 3, 1, 2, 3])